"""Report tools for the Report Analyst agent."""

from __future__ import annotations

import json
from pathlib import Path

from langchain_core.tools import tool

from core.data_store import DataStore
from utils.pptx_export import markdown_to_pptx

_data_store: DataStore | None = None


def set_data_store(store: DataStore) -> None:
    global _data_store
    _data_store = store


def _get_store() -> DataStore:
    if _data_store is None:
        raise RuntimeError("DataStore not initialized.")
    return _data_store


@tool
def generate_markdown_report(
    title: str,
    executive_summary: str,
    detailed_findings: str,
    impact_ease_matrix: str,
    recommendations: str,
    data_appendix: str,
) -> str:
    """Generate a structured markdown report from provided sections.

    Args:
        title: Report title.
        executive_summary: Top findings and key metrics summary.
        detailed_findings: Each finding with scores and evidence.
        impact_ease_matrix: Findings organized by impact vs ease quadrants.
        recommendations: Prioritized action items.
        data_appendix: Dataset info, filters, methodology notes.

    Returns:
        JSON with the DataStore key for the stored report.
    """
    store = _get_store()

    report = f"""# {title}

## Executive Summary

{executive_summary}

## Detailed Findings

{detailed_findings}

## Impact vs Ease Matrix

{impact_ease_matrix}

## Recommendations

{recommendations}

## Data Appendix

{data_appendix}

---
*Report generated by AgenticAnalytics*
"""

    key = store.store_text(
        "report_markdown",
        report,
        metadata={"title": title, "sections": 5},
    )

    return json.dumps({"report_key": key, "char_count": len(report)})


@tool
def export_to_pptx(report_key: str = "report_markdown", output_dir: str = "data") -> str:
    """Export a markdown report to PowerPoint.

    Args:
        report_key: DataStore key for the markdown report.
        output_dir: Directory to save the .pptx file.

    Returns:
        JSON with the path to the generated .pptx file.
    """
    store = _get_store()
    markdown_content = store.get_text(report_key)

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    output_path = out_dir / f"report_{store.session_id}.pptx"

    markdown_to_pptx(markdown_content, str(output_path))

    return json.dumps({"pptx_path": str(output_path)})


REPORT_TOOLS = [generate_markdown_report, export_to_pptx]
